# Generated by Django 4.2.7 on 2023-11-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='demo',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
