# Generated by Django 4.2.4 on 2023-11-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_demo_joined_date_demo_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='demo',
            name='phone',
        ),
    ]
