# Generated by Django 4.2.4 on 2023-11-25 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_demo_joined_date_remove_demo_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demo',
            new_name='Name',
        ),
    ]
