# Generated by Django 4.2.4 on 2023-11-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersinfo',
            name='joined_date',
        ),
        migrations.AddField(
            model_name='usersinfo',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
