# Generated by Django 4.2.4 on 2023-11-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usersinfo_joined_date_usersinfo_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersinfo',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
