# Generated by Django 4.2.4 on 2023-12-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usersinfo_is_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('content', models.CharField(max_length=500, null=True)),
                ('datePosted', models.DateField(null=True)),
                ('numLikes', models.IntegerField(default=0, null=True)),
                ('numComments', models.IntegerField(default=0, null=True)),
                ('numShares', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
