# Generated by Django 4.2.4 on 2023-12-01 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='username',
        ),
        migrations.AddField(
            model_name='posts',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
