# Generated by Django 4.2.4 on 2023-12-03 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_posts_dateposted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='datePosted',
            field=models.DateField(default=datetime.datetime(2023, 12, 2, 22, 6, 12, 199004)),
        ),
    ]
