# Generated by Django 4.2.4 on 2023-12-03 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_posts_dateposted_alter_usersinfo_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='datePosted',
            field=models.DateField(default=datetime.date(2023, 12, 2)),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 22, 16, 49, 29958)),
        ),
    ]
