# Generated by Django 4.2.4 on 2023-12-03 23:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_posts_dateposted_alter_usersinfo_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='datePosted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
