# Generated by Django 4.2.4 on 2023-12-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_posts_dateposted_alter_usersinfo_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
