# Generated by Django 4.2.4 on 2023-12-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_posts_firstname_posts_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
