# Generated by Django 4.2.4 on 2023-12-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_posts_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
