# Generated by Django 4.2.4 on 2023-12-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_posts_isliked'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='isFollowing',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
