# Generated by Django 4.2.4 on 2023-12-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_posts_isfollowing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
